### PR TITLE
Edit .env-default file to correct syntax

### PR DESCRIPTION
**Pull request by ehinman**
This PR is a simple change to the .env-default file to update the example syntax from `API_TOKEN=` to `GITHUB_TOKEN=`. Addresses issue #195.

### CODE REVIEW

**Review by willingc — APPROVED** [review]
Thanks for the contribution @ehinman. Sorry for the delay in reviewing. ✨

**Comment by willingc** [comment]
The test failure is unrelated to this PR. This should pass after #199 is merged.

**Comment by lwasser** [comment]
thank you both!! let's merge this @willingc (and btw you are always welcome to merge things ✨ )

**Comment by lwasser** [comment]
@all-contributors please add @ehinman for code, review

**Pull request merged**
