### PR TITLE
Split utilities test file into two to match the source files

### PR DESCRIPTION
**Pull request by willingc**
This small PR breaks up the existing test file for utilities into two test files following the refactor in #121 and #120. No tests were changed.

### CODE REVIEW

**Review by lwasser — APPROVED** [review]
@willingc this is great. i debated about this last night as well. it feels weird to have a single function in a module and then a single test in a test module. are we leaning in to readibility over how much content is in a module here? we can merge this as well.

**Comment by willingc** [comment]
@lwasser It's fine to have 1 function in a module or 1 test in a file. I tend to lean toward separation of concepts. If we had one file called `utils.py`, then I would create `test_utils.py` (which would include all utilities). Since we split the utils into two files which makes good sense `utils_clean.py` and `utils_parse.py`, I like to match the test files to the source file. It requires less thought on my part since I know my tests are almost always in a file `test_sourcefilename.py` when `sourcefilename.py` is the code file.

**Comment by willingc** [comment]
Keep the great questions coming too.

**Comment by lwasser** [comment]
Thank you @willingc !! That makes sense!!

**Pull request merged**
